### ISSUE TITLE
Posting Comments

### ISSUE THREAD

**Issue by atulg** [yesudeep/mils-secure#19]
The blog page where one can post comments, after posting the comments , they are not visible on the page.

**Comment by yesudeep** [comment]
Comments are visible at the end of only article pages.   Blog pages will not contain comments as they tend to grow very long and can distract the user from reading articles further down.

Also, can you please upload a screenshot of what the problem looks like and the 
browser/platform you were using when you saw this error.

**Comment by yesudeep** [comment]
Discussed and agreed upon as fixed.  Comments can appear only individual article pages.
