### ISSUE TITLE
Please rename "Edit" buttons in each profile in the users section to "View profile"

### ISSUE THREAD

**Issue by yesudeep** [yesudeep/mils-secure#6]
Atul thinks the "Edit" button is a bit misleading and it should be named "View profile".

**Comment by yesudeep** [comment]
I don't think naming it "View profile" is a good idea either, since the idea is to be able
to edit the profile.  I could possibly rename it "Edit Profile"

**Comment by atulg** [comment]
makes sense

**Comment by yesudeep** [comment]
Fixed.
